### PR TITLE
Return null when getting field value for image if inner item is not found

### PR DESCRIPTION
**Pull request by JRondeau16**
When an image has been deleted from Sitecore and is still being referenced by a Sitecore item, the inner item is null and cannot be found.

------------------------------------------------------------------------------------------------------------------------------------------

Server Error in '/' Application.

Value cannot be null.
Parameter name: innerItem

Description: An unhandled exception occurred. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: innerItem

Source Error: 

Line 20:         public override ActionResult Index()
Line 21:         {
Line 22: 	        var model = GetControllerItem<TruckDetailPage>();
Line 23: 			model.ShowEmployeeData = Request.QueryString["e"] == "1";
Line 24: 			model = _mapper.Map(model, _userProfileRespository.CurrentUser());            

Source File: d:\_APPLICATION\MYPROJ\src\MYPROJ.Web\MYPROJ\Controllers\TruckDetailController.cs    Line: 22 

Stack Trace: 

[ArgumentNullException: Value cannot be null.
Parameter name: innerItem]
   Sitecore.Data.Items.CustomItemBase..ctor(Item innerItem) +75
   Glass.Mapper.Sc.DataMappers.SitecoreFieldImageMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +263
   Glass.Mapper.Sc.DataMappers.<>c__DisplayClass3.<GetFieldValue>b__1(String x) +169
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +82
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +488
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +103
   Glass.Mapper.Sc.DataMappers.SitecoreFieldIEnumerableMapper.GetFieldValue(String fieldValue, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +753
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +154

[MapperException: Failed to map field AdditionalImages with value {E41C6F49-3B4B-48EC-A786-DF68CC008BC6}]
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.GetField(Field field, SitecoreFieldConfiguration config, SitecoreDataMappingContext context) +389
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapToProperty(AbstractDataMappingContext mappingContext) +352
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +99

[MapperException: Failed to map to property 'AdditionalImages' on type 'MYPROJ.Web.Models.TruckDetailPage']
   Glass.Mapper.AbstractDataMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +627
   Glass.Mapper.Sc.DataMappers.AbstractSitecoreFieldMapper.MapCmsToProperty(AbstractDataMappingContext mappingContext) +164
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +131

[MapperException: Failed to map property AdditionalImages on MYPROJ.Web.Models.TruckDetailPage]
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +545
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.<>c__DisplayClassb.<CreatePropertyExpression>b__a(Object obj, AbstractDataMappingContext context) +180
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +189

[MapperException: Failed to map properties on /sitecore/content/Home/Trucks/2014/08/28/09/42/2014 KENWORTH T800.]
   Glass.Mapper.Configuration.AbstractTypeConfiguration.MapPropertiesToObject(Object obj, IAbstractService service, AbstractTypeCreationContext context) +394
   Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.<>c__DisplayClass6.<Execute>b__0(Object target) +174
   Glass.Mapper.Sc.CastleWindsor.Pipelines.ObjectConstruction.WindsorConstruction.Execute(ObjectConstructionArgs args) +1924
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +197
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.<>c__DisplayClass3.<CreateTaskExpression>b__2(T args) +293
   Glass.Mapper.Pipelines.AbstractPipelineRunner`2.Run(T args) +81
   Glass.Mapper.AbstractService.InstantiateObject(AbstractTypeCreationContext abstractTypeCreationContext) +646
   Glass.Mapper.Sc.SitecoreService.CreateType(Type type, Item item, Boolean isLazy, Boolean inferType, Dictionary`2 parameters, Object[] constructorParameters) +754
   Glass.Mapper.Sc.SitecoreService.CreateType(Item item, Boolean isLazy, Boolean inferType) +215
   Glass.Mapper.Sc.SitecoreContext.GetCurrentItem(Boolean isLazy, Boolean inferType) +174
   Glass.Mapper.Sc.Web.Mvc.GlassController.GetControllerItem(Boolean isLazy, Boolean inferType) +312
   MYPROJ.Web.Controllers.TruckDetailController.Index() in d:\_APPLICATION\MYPROJ\src\MYPROJ.Web\MYPROJ\Controllers\TruckDetailController.cs:22
   lambda_method(Closure , ControllerBase , Object[] ) +81
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +242
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +39
   System.Web.Mvc.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12() +120
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +637
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +637
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +307
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +686

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34237

### CODE REVIEW

**Comment by JRondeau16** [comment]
Hey Mike,

I updated to the newest version of Glass Mapper and this no longer looks to be a problem.  You mind rejecting this?  

Also if you don't mind pointing me to the commit that you fixed this in, that would be awesome!

Thanks,

**Comment by mikeedwards83** [comment]
Looking at your code and what we have I think it might still be needed. Your problem might be resolved but I think that might be because of something else.

**Comment by mikeedwards83** [comment]
Ok just checked against my unit tests. You will see that we now go by teh GetField method:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/DataMappers/SitecoreFieldImageMapper.cs#L56

This doesn't call the GetFieldValue method any more.

We perform the null check here:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/DataMappers/SitecoreFieldImageMapper.cs#L81

**Comment by mikeedwards83** [comment]
Closing this issue as we won't be pulling in this commit.

**Pull request closed without merging**
