### PR TITLE
Sitecore 10.2.0 update

### PR DESCRIPTION
**Pull request by avwolferen**
Bits for updating Glass Mapper to Sitecore 10.2.0

There is still a caveat where Sitecore made a boo boo on the package dependency to Sitecore.Nexus.Consumption (should be >= 1.4.2 in stead of >=1.4.0) in Sitecore.Analytics. They already fixed the package dependencies in Sitecore.Kernel and Sitecore.Client.

Made the package Sitecore.Nexus conditional for Sitecore 10.2.0 because this has been refactored to the Sitecore.Kernel. 10.2.0 doesn't have a Sitecore.Nexus package anymore.
Condition used: <PackageReference Include="Sitecore.Nexus" Version="$(ScVersion)" Condition="'$(ScVersion)' != '10.2.0'" />

### CODE REVIEW

**Comment by avwolferen** [comment]
Hi,

Sitecore fixed the wrong dependency in the nuspec of Sitecore.Analytics this morning after I created the support ticket a couple of days ago.

Cheers

**Comment by muso31** [comment]
@mikeedwards83 this passes the 10.2 build pipeline 👍

**Comment by mikeedwards83** [comment]
Thanks @avwolferen  and @muso31 

@muso31 are you happy for me to merge?

**Comment by mikeedwards83** [comment]
I also notice that some of the conditional builds go back to SC90. We could drop support for < SC90 and remove these conditionals.

**Comment by muso31** [comment]
> Thanks @avwolferen and @muso31
> 
> @muso31 are you happy for me to merge?

Yes, happy to merge

**Comment by avwolferen** [comment]
Hi, any chances on merging this soon or are there any additional checks to do?

**Pull request merged**
